allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  f638c670-3393-4f0c-a617-8360b92f1572:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-18T16:48:16+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a1917f55-1534-44e6-9159-e330ae97592e # Title
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7da9b93-06ce-4e00-b71d-ec2602df5698
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-18T16:48:16+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2fa12a9c-e0ff-4404-943b-d18c0f0f5f4e # Intro
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23815871-5ea3-4397-86ce-35adbd4f53ab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-18T17:08:39+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7c39293b-eed9-4ccd-9fef-54ef45046927 # Banner Image
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8f5a774-0b1e-4d64-8ff0-c0d67c162a4e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-25T15:31:07+00:00'
            elementCondition: null
            heading: 'Section Activities'
            type: craft\fieldlayoutelements\Heading
            uid: 941c3626-0c49-4679-95ac-88d920aedfdf
            userCondition: null
          -
            dateAdded: '2026-03-25T13:51:51+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7b5e2946-9b1e-4251-bd6d-040141e14d0b # Title
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 635eba8a-cbf9-4551-a0a7-576a91c3f1f3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-25T13:51:51+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1dcdcbb0-58d5-40f1-bd6d-4f3f1e32e5dd # Intro
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7cebecb0-fa05-4389-9eda-9261f7028468
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-25T13:51:51+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 11157680-9ec9-4a9f-ac82-6e1137974453 # Activites
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d19a6ed-10b0-40bf-b1f6-0ff3f48edccc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-25T15:31:07+00:00'
            elementCondition: null
            heading: 'Section Projects'
            type: craft\fieldlayoutelements\Heading
            uid: c7bb07f2-b145-49c3-b0ea-0f972ecf7076
            userCondition: null
          -
            dateAdded: '2026-03-25T15:31:07+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c70bd9ec-4a2e-4602-b512-cf6a522c00d0 # Title
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9c205db-36dc-4efc-8191-7cf595fd5185
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-25T15:31:07+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 44f3d9f2-7415-4c94-95ea-69d157eab7e8 # Intro
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70c6955c-512f-4d0f-879c-b66f559d3f69
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a31bdc4-d2ff-40df-8012-777955c0231f
        userCondition: null
    thumbFieldKey: null
handle: homepage
hasTitleField: false
icon: null
name: homepage
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Homepage
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: Homepage
