allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  4653b82c-d6e4-4f0c-b391-079073da2f45:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-15T12:58:54+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a00a3b14-d4d5-4fb8-b3e4-14df03b96eb3 # Service Provider
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c59bee9-fa78-431c-91b7-6cd4a7d02d49
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-08T16:01:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7a783a29-7156-4483-b41a-4d55d2fbccdb # Video ID
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5de05f78-34b6-4c28-a786-a983fc85af88
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T13:18:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 84b649ee-bcff-4fbe-a0dc-875dd3e1509d # Video Caption
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09676648-780e-498c-a300-70887680cae2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9fa585f5-55af-422d-8704-58d1fd836e03
        userCondition: null
    thumbFieldKey: null
handle: mxBlockVideo
hasTitleField: false
icon: video
name: Video
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
