columnSuffix: null
handle: commonBannerImage
instructions: null
name: 'Banner Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:65166879-68f5-4a7f-a618-d9c979404621' # Project Images
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:22cd74bf-020d-4724-aa7e-fab6166f847b' # Pages Banners
  restrictedLocationSubpath: null
  selectionLabel: null
  showSearchInput: false
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
