columnSuffix: null
handle: mxServiceProvider
instructions: 'Choose a service provider'
name: 'Service Provider'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - YouTube
        -
          - value
          - youtube
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Vimeo
        -
          - value
          - vimeo
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
