columnSuffix: null
handle: mxValueTitle
instructions: null
name: Title
searchable: false
settings:
  byteLimit: null
  charLimit: 64
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
