dateModified: 1775651899
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      page: Entries
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: true
      key: singles
      page: Entries
      tableAttributes:
        - status
        - link
      type: native
    -
      heading: Pages
      key: 'heading:b6a708e5-c94e-45ee-a63c-e0e42c3d0a4b'
      page: Entries
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 5bd658d5-7c96-42df-8772-0e5d3fb774b8
            values:
              - aa27ffac-cd6f-48e6-abcc-c17ad727056d # Homepage
              - 7d134702-58b7-44fe-9a2c-8202781ece8c # Projects Page
              - bc566a59-9477-4399-b66c-855e13b8094e # About Page
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      key: 'custom:4956574a-cd21-4686-8293-edc741b76696'
      label: Pages
      page: Entries
      tableAttributes: '-'
      type: custom
    -
      heading: Channels
      key: 'heading:058c676f-688f-4016-b3f3-1a2457d9645c'
      page: Entries
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: table
      disabled: false
      key: 'section:c3d44bc9-cd36-4f01-a8b9-780009eeac96' # Projects
      page: Entries
      tableAttributes:
        - status
        - postDate
        - 'field:bb20e26f-e0ca-46d3-96d3-db26f1306a8d' # Subtitle
      type: native
    -
      heading: Navigations
      key: 'heading:9d80185a-3b62-45eb-8984-152929f11e94'
      page: Entries
      type: heading
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:7746ddac-ea86-4e70-bf7a-4f1e55ca102e' # Main Nav
      page: Entries
      tableAttributes:
        - status
        - link
      type: native
    -
      key: 'section:e9d59d34-8ff9-41f3-9b89-2d6abad1cb90' # Legal Nav
      page: Entries
      type: native
    -
      heading: Company
      key: 'heading:92b7258f-634b-445b-a0ea-a2f71f0c5c25'
      page: Entries
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 8122999e-7ed3-432c-9ce9-65bdea20d39f
            values:
              - d560cc9f-ac1a-4672-b2a5-765cbaf2c097 # Contact
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      key: 'custom:fece20e1-97ea-4d7a-9101-00824686213f'
      label: Contact
      page: Entries
      tableAttributes: '-'
      type: custom
email:
  fromEmail: kerya.nguyen@etu.iad-arts.be
  fromName: zodiak
  transportType: craft\mail\transportadapters\Sendmail
fs:
  legalDocs:
    hasUrls: true
    name: 'Legal Docs'
    settings:
      path: '@assetsBasePath/legal_files'
    type: craft\fs\Local
    url: '@assetsBaseUrl/legal_files'
  pagesBanners:
    hasUrls: true
    name: 'Pages Banners'
    settings:
      path: '@assetsBasePath/pages_banners'
    type: craft\fs\Local
    url: '@assetsBaseUrl/pages_banners'
  projectsImages:
    hasUrls: true
    name: 'Projects Images'
    settings:
      path: '@assetsBasePath/projects_images'
    type: craft\fs\Local
    url: '@assetsBaseUrl/projects_images'
  socialIcons:
    hasUrls: true
    name: 'Social Icons'
    settings:
      path: '@assetsBasePath/social_icons'
    type: craft\fs\Local
    url: '@assetsBaseUrl/social_icons'
meta:
  __names__:
    0bc00463-b8d9-457c-94dd-421a357df51a: Activities # Activities
    1b6ffa27-4972-428e-b5e8-5459b8f860de: 'Legal Docs' # Legal Docs
    1dcdcbb0-58d5-40f1-bd6d-4f3f1e32e5dd: Intro # Intro
    2fa12a9c-e0ff-4404-943b-d18c0f0f5f4e: Intro # Intro
    4b82dbba-ea70-404f-954a-e840ff5adb83: 'Social Media' # Social Media
    6c360c4f-4a2f-4abf-9b05-e01a96c97c32: Contact # Contact
    7a0839a3-ba27-4ad4-a444-91badb493b8d: 'Social url' # Social url
    7ad7e7fb-40f1-412a-9ee4-2a1438b7f4b0: Phone # Phone
    7b5e2946-9b1e-4251-bd6d-040141e14d0b: Title # Title
    7c39293b-eed9-4ccd-9fef-54ef45046927: 'Banner Image' # Banner Image
    7d134702-58b7-44fe-9a2c-8202781ece8c: 'Projects Page' # Projects Page
    8a4a8ea9-98bc-4b41-b708-729f70fb6aa1: Email # Email
    11eb6c53-5e08-483a-aa33-ef3e5dfc2456: zodiak # zodiak
    22cd74bf-020d-4724-aa7e-fab6166f847b: 'Pages Banners' # Pages Banners
    41b3d4ab-7806-43c0-a28e-79cfbb407d09: 'Social Media' # Social Media
    44f3d9f2-7415-4c94-95ea-69d157eab7e8: Intro # Intro
    47c911c4-4b30-4db7-9321-56f4d39085f9: homepage # homepage
    50afdb25-510f-491f-abbd-b31010db0395: 'Social Icon' # Social Icon
    99f562bb-763e-4670-b29a-ae7420cf657f: Address # Address
    138f0bd5-183c-480a-acc3-8cc9cb404e25: Text # Text
    6700c772-ae03-4a90-80fc-4ff1e4c5a5d6: 'About Page' # About Page
    7746ddac-ea86-4e70-bf7a-4f1e55ca102e: 'Main Nav' # Main Nav
    72322d43-076d-4415-8dee-41fd46bbd6b4: nav # nav
    85054f16-a647-4e4d-acc2-85259bedbdcf: Image # Image
    11157680-9ec9-4a9f-ac82-6e1137974453: Activites # Activites
    53233200-875a-49c4-8a59-f791b0c59dc7: 'Social Icons' # Social Icons
    65166879-68f5-4a7f-a618-d9c979404621: 'Project Images' # Project Images
    a96f56b3-4404-44e4-aebb-ce6e7fa3ac47: Title # Title
    a454a20e-2ec1-4b80-86e9-485e852e5722: Link # Link
    a1917f55-1534-44e6-9159-e330ae97592e: Title # Title
    aa27ffac-cd6f-48e6-abcc-c17ad727056d: Homepage # Homepage
    bb20e26f-e0ca-46d3-96d3-db26f1306a8d: Subtitle # Subtitle
    bc566a59-9477-4399-b66c-855e13b8094e: 'About Page' # About Page
    bd941b2b-afd7-417c-a8f0-7c9a2c47bc56: 'Public Schema' # Public Schema
    be6092aa-f7fe-4a07-90c4-d2684bd98478: Title # Title
    c3d44bc9-cd36-4f01-a8b9-780009eeac96: Projects # Projects
    c70bd9ec-4a2e-4602-b512-cf6a522c00d0: Title # Title
    c87d9797-08cc-4928-a9c8-363e490a8db0: Projects # Projects
    d560cc9f-ac1a-4672-b2a5-765cbaf2c097: Contact # Contact
    daf5c4fa-14fd-425a-b0bf-f47763e04d64: 'Social Label' # Social Label
    e9d59d34-8ff9-41f3-9b89-2d6abad1cb90: 'Legal Nav' # Legal Nav
    e9fa6b9b-ed8c-436d-bda0-6ef824f5637a: 'Projects Page' # Projects Page
    f430b339-9348-455d-80ab-66ab0d1a0285: zodiak # zodiak
system:
  edition: pro
  live: true
  name: zodiak
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
