defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 47c911c4-4b30-4db7-9321-56f4d39085f9 # homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  f430b339-9348-455d-80ab-66ab0d1a0285: # zodiak
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
