defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 72322d43-076d-4415-8dee-41fd46bbd6b4 # nav
handle: mainnav
maxAuthors: 1
name: 'Main Nav'
propagationMethod: all
siteSettings:
  f430b339-9348-455d-80ab-66ab0d1a0285: # zodiak
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: bd8d9056-15d0-4315-9d6b-6ae2c77fb943
type: structure
